apiVersion: v1
kind: Service
metadata:
  name: app-nginx
  namespace: stage
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: app-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ .Values.app_nginx_service.nodeport }}